DefaultContentLanguage = 'en'
baseURL = 'http://linux.pistasjis.net/'
languageCode = 'en-us'
title = 'Pistachio Linux'

theme = 'pistachio'

[languages]
    [languages.en]
        PistachioLinux = 'Pistachio Linux'
        PistachioVersionTag = 'beta'
        blog = 'The Pistachio Blog'
        WhatIsPistachio = 'Pistachio Linux is an all new Linux distribution built for WSL. With Pistachio, you can run any Linux distro, without ever needing to install them.'
        madewith = 'Made with ❤️ and uhh 🍦 by <a href="https://pistasjis.net">Pistasj</a>' 
        dateformat = 'Jan 2, 2006'
        notfoundmessage = "Oops, looks like you're lost."
        notfoundlink = 'Go back home'
    [langauges.no]
        PistachioLinux = 'Pistachio Linux'
        PistachioVersionTag = 'beta'
        WhatIsPistachio = 'Pistachio Linux er en helt ny Linux distribusjon bygget for WSL. Med Pistachio kan du kjøre hvilken som helst Linux distro, uten å noen gang trenge å installere dem.'
        madewith = 'Laget med ❤️ og øhh 🍦 av <a href="https://pistasjis.net">Pistasj</a>'

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files